"""SEARCH_COMPACT — same scientific runtime, bounded evidence notebook.

Evidence mode is orthogonal to LIVE/FAST/MAX/HEADLESS execution presentation.
"""
from __future__ import annotations

EVIDENCE_FULL_SCIENTIFIC = "FULL_SCIENTIFIC"
EVIDENCE_SEARCH_COMPACT = "SEARCH_COMPACT"
EVIDENCE_MODES = (EVIDENCE_FULL_SCIENTIFIC, EVIDENCE_SEARCH_COMPACT)

DEFAULT_PRE_WINDOW = 32
DEFAULT_POST_WINDOW = 32
DEFAULT_MAX_CANDIDATES = 8
DEFAULT_TRIGGER_COOLDOWN = 16

ANALYZER_COMPAT_FULL = "ANALYZER_FULL_COMPATIBLE"
ANALYZER_COMPAT_CANDIDATE = "CANDIDATE_WINDOW_COMPATIBLE"
ANALYZER_COMPAT_COMPACT_ONLY = "COMPACT_ONLY"
