/** Canonical Observer model presets. One selector: preset owns model_line. */

export const UI_PRESET_TIKTAALIK_BETA31 = 'MM 1.0 — Tiktaalik Beta 3.1';
export const UI_PRESET_TIKTAALIK_BETA3 = 'MM 1.0 — Tiktaalik Public Beta 3';
export const UI_PRESET_TIKTAALIK = 'MM 1.0 — Tiktaalik';
export const UI_PRESET_ACANTHOSTEGA_PHASE0 = 'Acanthostega Phase 0';
export const UI_PRESET_ACANTHOSTEGA_PHASE_A = 'Acanthostega Phase A Gentle';
export const UI_PRESET_ACANTHOSTEGA_MATERIALS = 'Acanthostega Phase A Materials';
export const UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION = 'Acanthostega Phase A Material Vision';
export const UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP = 'Acanthostega Phase A Single Grasp';
export const UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP = 'Acanthostega Phase A Bilateral Grasp';
export const UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER = 'Acanthostega Phase A Bring Together';
export const UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE = 'Acanthostega Phase A Composition Merge';
export const UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES = 'Acanthostega Phase A Material Properties';
export const UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION = 'Acanthostega Phase A Surface Deposition';
export const UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION = 'Acanthostega Phase A Surface Traction';
export const UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE = 'Acanthostega Phase A Traction Experience';
export const UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION = 'Acanthostega Phase A Traction Adaptation';
export const UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL = 'Acanthostega Phase A Surface Optical';
export const UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL = 'Acanthostega Phase B World Material Transactions';
export const UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT = 'Acanthostega Phase B Multi-Content Index';
export const UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS = 'Acanthostega Phase B Procedural Columns';
export const UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER = 'Acanthostega Phase B Column Transfer';
export const UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL = 'Acanthostega Phase B Local Physical Signal';
export const UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS = 'Acanthostega Phase B Contact Acoustics';
export const UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS = 'Acanthostega Phase B Free Object Kinematics';
export const UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT = 'Acanthostega Phase B Body Object Contact';
export const UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE = 'Acanthostega Phase B Body Object Impulse';
export const UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS = 'Acanthostega Phase B Object Impact Acoustics';
export const UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT = 'Acanthostega Phase B Object Object Contact';
export const UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE = 'Acanthostega Phase B Object Object Impulse';
export const UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS = 'Acanthostega Phase B Object Object Impact Acoustics';
export const UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT = 'Acanthostega Phase B Held Object Foreign Body Contact';
export const UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_TRANSLATIONAL_IMPULSE = 'Acanthostega Phase B Held Object Translational Impulse';
export const UI_PRESET_ACANTHOSTEGA_EFFECTOR_WORK_ACCOUNTING = 'Acanthostega Phase B Effector Work Accounting';
export const UI_PRESET_ACANTHOSTEGA_FLAT_GROUND_GRAVITY = 'Acanthostega Phase C Flat Ground Gravity';
export const UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_GROUND_FRICTION = 'Acanthostega Phase C Free Object Ground Friction';
export const UI_PRESET_ACANTHOSTEGA_SURFACE_ELEVATION_SUPPORT = 'Acanthostega Phase C Surface Elevation Support';
export const UI_PRESET_ACANTHOSTEGA_BODY_NORMAL_LOAD_TRACTION = 'Acanthostega Phase C Body Normal-Load Traction';
export const UI_PRESET_ACANTHOSTEGA_CONTINUOUS_SURFACE_GEOMETRY = 'Acanthostega Phase C Continuous Surface Geometry';
export const UI_PRESET_ACANTHOSTEGA_STATIC_TRACTION = 'Acanthostega Phase C Static Traction';
export const UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_STATIC_TRACTION = 'Acanthostega Phase C Free Object Static Traction';
export const UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT = 'Acanthostega Phase C Radius-Aware Support';
export const UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT = 'Acanthostega Phase C SES Decomposition Contract';
export const UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER = 'Acanthostega Phase C SES Runtime Classifier';
export const UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP = 'Acanthostega Phase C Radius-Aware Face Sweep';
export const UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW = 'Acanthostega Phase C Diagnostic Normal-Load Shadow';
export const UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW = 'Acanthostega Phase C Continuous Gravitational PE Diagnostic Shadow';
export const UI_PRESET_ACANTHOSTEGA_CONTINUOUS_PE_POLICY_C = 'Acanthostega Phase C Continuous PE Policy C';
export const UI_PRESET_ACANTHOSTEGA_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW = 'Acanthostega Phase C Tangent Gravity Diagnostic Shadow';
export const UI_PRESET_ACANTHOSTEGA_COHERENT_SLOPE_DYNAMICS = 'Acanthostega Phase C Coherent Slope Dynamics';
export const UI_PRESET_ACANTHOSTEGA_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION = 'Acanthostega Beta 4 Conservative Surface Material Separation';
export const UI_PRESET_ACANTHOSTEGA_EFFECTOR_TERRAIN_CONTACT_GEOMETRY = 'Acanthostega Beta 4 Effector Terrain Contact Geometry';
export const UI_PRESET_ACANTHOSTEGA_MANIPULATOR_RELATIVE_WORLD_ACTUATION = 'Acanthostega Beta 4 Manipulator Relative World Actuation';
export const UI_PRESET_ACANTHOSTEGA_EFFECTOR_BOUNDED_ACTUATOR_EFFORT = 'Acanthostega Beta 4 Effector Bounded Actuator Effort';
export const UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE = 'Acanthostega Beta 4 Surface Exertion Terrain Material Resistance';
export const UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY = 'Acanthostega Beta 4 Held Object Terrain Contact';
export const UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION = 'Acanthostega Beta 4 Held Object Terrain Mechanical Transmission';
export const UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION = 'Acanthostega Beta 4 Held-Mediated Surface Exertion Integration';
export const UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT = 'Acanthostega Beta 4 Detached Terrain Material Initial Placement';
export const UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR = 'Acanthostega Beta 4 BNLT MOVE Breakaway Locomotion Repair';
export const UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION = 'Acanthostega Beta 4 Repeated Conservative Surface-Column Separation';
export const UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION = 'Acanthostega Beta 4 Active Locomotion Traction vs Sliding Friction';
export const UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT = 'Acanthostega Beta 4 Event-Driven Crowded Placement Retry Contract';
export const UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS = 'Acanthostega Beta 4 Detached Material Amount-Scaled Collision Radius';
export const UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION = 'Acanthostega Beta 4 Held COMBINE Radius Resize Transaction';
export const UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION = 'Acanthostega Beta 4 Held Deposition Radius Shrink Transaction';
export const UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT = 'Acanthostega Beta 4 Free-Space State And PE Authority Contract';
export const UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE = 'Acanthostega Beta 4 Vertical Terrain Landing Contact Response';
export const UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION = 'Acanthostega Beta 4 Vertical Impact Acoustic Emission';
export const UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION = 'Acanthostega Beta 4 Release And Excavation Support Loss Integration';
export const UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7 = 'Acanthostega · Volumetric World · VW7';
export const UI_PRESET_ACANTHOSTEGA_BETA4 = 'Acanthostega Beta 4.0';
export const UI_PRESET_CUSTOM = 'CUSTOM';

export const PUBLIC_PRESET_TIKTAALIK_BETA31 = 'TIKTAALIK_BETA31';
export const PUBLIC_PRESET_BETA3 = 'BETA3_RECOMMENDED';
export const PUBLIC_PRESET_ACANTHOSTEGA_PHASE0 = 'ACANTHOSTEGA_PHASE0';
export const PUBLIC_PRESET_ACANTHOSTEGA_GENTLE = 'ACANTHOSTEGA_PHASE_A_GENTLE';
export const PUBLIC_PRESET_ACANTHOSTEGA_MATERIALS = 'ACANTHOSTEGA_PHASE_A_MATERIALS';
export const PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_VISION = 'ACANTHOSTEGA_PHASE_A_MATERIAL_VISION';
export const PUBLIC_PRESET_ACANTHOSTEGA_SINGLE_GRASP = 'ACANTHOSTEGA_PHASE_A_SINGLE_GRASP';
export const PUBLIC_PRESET_ACANTHOSTEGA_BILATERAL_GRASP = 'ACANTHOSTEGA_PHASE_A_BILATERAL_GRASP';
export const PUBLIC_PRESET_ACANTHOSTEGA_BRING_TOGETHER = 'ACANTHOSTEGA_PHASE_A_BRING_TOGETHER';
export const PUBLIC_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE = 'ACANTHOSTEGA_PHASE_A_COMPOSITION_MERGE';
export const PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES = 'ACANTHOSTEGA_PHASE_A_MATERIAL_PROPERTIES';
export const PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION = 'ACANTHOSTEGA_PHASE_A_SURFACE_DEPOSITION';
export const PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_TRACTION = 'ACANTHOSTEGA_PHASE_A_SURFACE_TRACTION';
export const PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE = 'ACANTHOSTEGA_PHASE_A_TRACTION_EXPERIENCE';
export const PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION = 'ACANTHOSTEGA_PHASE_A_TRACTION_ADAPTATION';
export const PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL = 'ACANTHOSTEGA_PHASE_A_SURFACE_OPTICAL';
export const PUBLIC_PRESET_ACANTHOSTEGA_WORLD_MATERIAL = 'ACANTHOSTEGA_PHASE_B_WORLD_MATERIAL_TRANSACTIONS';
export const PUBLIC_PRESET_ACANTHOSTEGA_MULTI_CONTENT = 'ACANTHOSTEGA_PHASE_B_MULTI_CONTENT_INDEX';
export const PUBLIC_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS = 'ACANTHOSTEGA_PHASE_B_PROCEDURAL_COLUMNS';
export const PUBLIC_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER = 'ACANTHOSTEGA_PHASE_B_COLUMN_TRANSFER';
export const PUBLIC_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL = 'ACANTHOSTEGA_PHASE_B_LOCAL_SIGNAL';
export const PUBLIC_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS = 'ACANTHOSTEGA_PHASE_B_CONTACT_ACOUSTICS';
export const PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS = 'ACANTHOSTEGA_PHASE_B_FREE_OBJECT_KINEMATICS';
export const PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT = 'ACANTHOSTEGA_PHASE_B_BODY_OBJECT_CONTACT';
export const PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE = 'ACANTHOSTEGA_PHASE_B_BODY_OBJECT_IMPULSE';
export const PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS = 'ACANTHOSTEGA_PHASE_B_OBJECT_IMPACT_ACOUSTICS';
export const PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT = 'ACANTHOSTEGA_PHASE_B_OBJECT_OBJECT_CONTACT';
export const PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE = 'ACANTHOSTEGA_PHASE_B_OBJECT_OBJECT_IMPULSE';
export const PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS = 'ACANTHOSTEGA_PHASE_B_OBJECT_OBJECT_IMPACT_ACOUSTICS';
export const PUBLIC_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT = 'ACANTHOSTEGA_PHASE_B_HELD_OBJECT_FOREIGN_BODY_CONTACT';
export const PUBLIC_PRESET_ACANTHOSTEGA_HELD_OBJECT_TRANSLATIONAL_IMPULSE = 'ACANTHOSTEGA_PHASE_B_HELD_OBJECT_TRANSLATIONAL_IMPULSE';
export const PUBLIC_PRESET_ACANTHOSTEGA_EFFECTOR_WORK_ACCOUNTING = 'ACANTHOSTEGA_PHASE_B_EFFECTOR_WORK_ACCOUNTING';
export const PUBLIC_PRESET_ACANTHOSTEGA_FLAT_GROUND_GRAVITY = 'ACANTHOSTEGA_PHASE_C_FLAT_GROUND_GRAVITY';
export const PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_GROUND_FRICTION = 'ACANTHOSTEGA_PHASE_C_FREE_OBJECT_GROUND_FRICTION';
export const PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_ELEVATION_SUPPORT = 'ACANTHOSTEGA_PHASE_C_SURFACE_ELEVATION_SUPPORT';
export const PUBLIC_PRESET_ACANTHOSTEGA_BODY_NORMAL_LOAD_TRACTION = 'ACANTHOSTEGA_PHASE_C_BODY_NORMAL_LOAD_TRACTION';
export const PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_SURFACE_GEOMETRY = 'ACANTHOSTEGA_PHASE_C_CONTINUOUS_SURFACE_GEOMETRY';
export const PUBLIC_PRESET_ACANTHOSTEGA_STATIC_TRACTION = 'ACANTHOSTEGA_PHASE_C_STATIC_TRACTION';
export const PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_STATIC_TRACTION = 'ACANTHOSTEGA_PHASE_C_FREE_OBJECT_STATIC_TRACTION';
export const PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT = 'ACANTHOSTEGA_PHASE_C_RADIUS_AWARE_SUPPORT';
export const PUBLIC_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT = 'ACANTHOSTEGA_PHASE_C_SES_DECOMPOSITION_CONTRACT';
export const PUBLIC_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER = 'ACANTHOSTEGA_PHASE_C_SES_RUNTIME_CLASSIFIER';
export const PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP = 'ACANTHOSTEGA_PHASE_C_RADIUS_AWARE_FACE_SWEEP';
export const PUBLIC_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW = 'ACANTHOSTEGA_PHASE_C_DIAGNOSTIC_NORMAL_LOAD_SHADOW';
export const PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW = 'ACANTHOSTEGA_PHASE_C_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW';
export const PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_PE_POLICY_C = 'ACANTHOSTEGA_PHASE_C_CONTINUOUS_PE_POLICY_C';
export const PUBLIC_PRESET_ACANTHOSTEGA_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW = 'ACANTHOSTEGA_PHASE_C_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW';
export const PUBLIC_PRESET_ACANTHOSTEGA_COHERENT_SLOPE_DYNAMICS = 'ACANTHOSTEGA_PHASE_C_COHERENT_SLOPE_DYNAMICS';
export const PUBLIC_PRESET_ACANTHOSTEGA_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION = 'ACANTHOSTEGA_BETA4_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION';
export const PUBLIC_PRESET_ACANTHOSTEGA_EFFECTOR_TERRAIN_CONTACT_GEOMETRY = 'ACANTHOSTEGA_BETA4_EFFECTOR_TERRAIN_CONTACT_GEOMETRY';
export const PUBLIC_PRESET_ACANTHOSTEGA_MANIPULATOR_RELATIVE_WORLD_ACTUATION = 'ACANTHOSTEGA_BETA4_MANIPULATOR_RELATIVE_WORLD_ACTUATION';
export const PUBLIC_PRESET_ACANTHOSTEGA_EFFECTOR_BOUNDED_ACTUATOR_EFFORT = 'ACANTHOSTEGA_BETA4_EFFECTOR_BOUNDED_ACTUATOR_EFFORT';
export const PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE = 'ACANTHOSTEGA_BETA4_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE';
export const PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY = 'ACANTHOSTEGA_BETA4_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY';
export const PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION = 'ACANTHOSTEGA_BETA4_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION';
export const PUBLIC_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION = 'ACANTHOSTEGA_BETA4_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION';
export const PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT = 'ACANTHOSTEGA_BETA4_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT';
export const PUBLIC_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR = 'ACANTHOSTEGA_BETA4_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR';
export const PUBLIC_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION = 'ACANTHOSTEGA_BETA4_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION';
export const PUBLIC_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION = 'ACANTHOSTEGA_BETA4_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION';
export const PUBLIC_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT = 'ACANTHOSTEGA_BETA4_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT';
export const PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS = 'ACANTHOSTEGA_BETA4_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS';
export const PUBLIC_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION = 'ACANTHOSTEGA_BETA4_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION';
export const PUBLIC_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION = 'ACANTHOSTEGA_BETA4_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION';
export const PUBLIC_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT = 'ACANTHOSTEGA_BETA4_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT';
export const PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE = 'ACANTHOSTEGA_BETA4_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE';
export const PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION = 'ACANTHOSTEGA_BETA4_VERTICAL_IMPACT_ACOUSTIC_EMISSION';
export const PUBLIC_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION = 'ACANTHOSTEGA_BETA4_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION';
export const PUBLIC_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7 = 'ACANTHOSTEGA_BETA4_VOLUMETRIC_WORLD_VW7';
export const PUBLIC_PRESET_ACANTHOSTEGA_BETA4 = 'ACANTHOSTEGA_BETA4';

export const CANONICAL_MODEL_PRESETS = [
  UI_PRESET_TIKTAALIK_BETA31,
  UI_PRESET_ACANTHOSTEGA_PHASE0,
  UI_PRESET_ACANTHOSTEGA_PHASE_A,
  UI_PRESET_ACANTHOSTEGA_MATERIALS,
  UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION,
  UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP,
  UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP,
  UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER,
  UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE,
  UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES,
  UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION,
  UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION,
  UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE,
  UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION,
  UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL,
  UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL,
  UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT,
  UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS,
  UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER,
  UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL,
  UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS,
  UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS,
  UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT,
  UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE,
  UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS,
  UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT,
  UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE,
  UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS,
  UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT,
  UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_TRANSLATIONAL_IMPULSE,
  UI_PRESET_ACANTHOSTEGA_EFFECTOR_WORK_ACCOUNTING,
  UI_PRESET_ACANTHOSTEGA_FLAT_GROUND_GRAVITY,
  UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_GROUND_FRICTION,
  UI_PRESET_ACANTHOSTEGA_SURFACE_ELEVATION_SUPPORT,
  UI_PRESET_ACANTHOSTEGA_BODY_NORMAL_LOAD_TRACTION,
  UI_PRESET_ACANTHOSTEGA_CONTINUOUS_SURFACE_GEOMETRY,
  UI_PRESET_ACANTHOSTEGA_STATIC_TRACTION,
  UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_STATIC_TRACTION,
  UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT,
  UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT,
  UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER,
  UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP,
  UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW,
  UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW,
  UI_PRESET_ACANTHOSTEGA_CONTINUOUS_PE_POLICY_C,
  UI_PRESET_ACANTHOSTEGA_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW,
  UI_PRESET_ACANTHOSTEGA_COHERENT_SLOPE_DYNAMICS,
  UI_PRESET_ACANTHOSTEGA_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION,
  UI_PRESET_ACANTHOSTEGA_EFFECTOR_TERRAIN_CONTACT_GEOMETRY,
  UI_PRESET_ACANTHOSTEGA_MANIPULATOR_RELATIVE_WORLD_ACTUATION,
  UI_PRESET_ACANTHOSTEGA_EFFECTOR_BOUNDED_ACTUATOR_EFFORT,
  UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE,
  UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY,
  UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION,
  UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION,
  UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT,
  UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR,
  UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION,
  UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION,
  UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT,
  UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS,
  UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION,
  UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION,
  UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT,
  UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE,
  UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION,
  UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION,
  UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7,
  UI_PRESET_ACANTHOSTEGA_BETA4,
] as const;

/** Normal user model selector: exactly two complete public models. */
export const UI_PUBLIC_LABEL_TIKTAALIK_BETA31 = 'Tiktaalik Beta 3.1';
export const PUBLIC_MODEL_PRESETS = [
  UI_PUBLIC_LABEL_TIKTAALIK_BETA31,
  UI_PRESET_ACANTHOSTEGA_BETA4,
] as const;

export function isPublicModelSelectorEntry(preset: string | null | undefined): boolean {
  return (
    preset === UI_PUBLIC_LABEL_TIKTAALIK_BETA31
    || preset === UI_PRESET_TIKTAALIK_BETA31
    || preset === UI_PRESET_ACANTHOSTEGA_BETA4
  );
}

export function publicPresetFromUi(preset: string): string | undefined {
  if (preset === UI_PRESET_TIKTAALIK_BETA3) return PUBLIC_PRESET_BETA3;
  if (preset === UI_PUBLIC_LABEL_TIKTAALIK_BETA31 || preset === UI_PRESET_TIKTAALIK_BETA31) return PUBLIC_PRESET_TIKTAALIK_BETA31;
  if (preset === UI_PRESET_ACANTHOSTEGA_PHASE0) return PUBLIC_PRESET_ACANTHOSTEGA_PHASE0;
  if (preset === UI_PRESET_ACANTHOSTEGA_PHASE_A) return PUBLIC_PRESET_ACANTHOSTEGA_GENTLE;
  if (preset === UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION) return PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_VISION;
  if (preset === UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP) return PUBLIC_PRESET_ACANTHOSTEGA_SINGLE_GRASP;
  if (preset === UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP) return PUBLIC_PRESET_ACANTHOSTEGA_BILATERAL_GRASP;
  if (preset === UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER) return PUBLIC_PRESET_ACANTHOSTEGA_BRING_TOGETHER;
  if (preset === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW) return PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW;
  if (preset === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_PE_POLICY_C) return PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_PE_POLICY_C;
  if (preset === UI_PRESET_ACANTHOSTEGA_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW) return PUBLIC_PRESET_ACANTHOSTEGA_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW;
  if (preset === UI_PRESET_ACANTHOSTEGA_COHERENT_SLOPE_DYNAMICS) return PUBLIC_PRESET_ACANTHOSTEGA_COHERENT_SLOPE_DYNAMICS;
  if (preset === UI_PRESET_ACANTHOSTEGA_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION) return PUBLIC_PRESET_ACANTHOSTEGA_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION;
  if (preset === UI_PRESET_ACANTHOSTEGA_EFFECTOR_TERRAIN_CONTACT_GEOMETRY) return PUBLIC_PRESET_ACANTHOSTEGA_EFFECTOR_TERRAIN_CONTACT_GEOMETRY;
  if (preset === UI_PRESET_ACANTHOSTEGA_MANIPULATOR_RELATIVE_WORLD_ACTUATION) return PUBLIC_PRESET_ACANTHOSTEGA_MANIPULATOR_RELATIVE_WORLD_ACTUATION;
  if (preset === UI_PRESET_ACANTHOSTEGA_EFFECTOR_BOUNDED_ACTUATOR_EFFORT) return PUBLIC_PRESET_ACANTHOSTEGA_EFFECTOR_BOUNDED_ACTUATOR_EFFORT;
  if (preset === UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE) return PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE;
  if (preset === UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY) return PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY;
  if (preset === UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION) return PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION;
  if (preset === UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT) return PUBLIC_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT;
  if (preset === UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION) return PUBLIC_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION;
  if (preset === UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION) return PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION;
  if (preset === UI_PRESET_ACANTHOSTEGA_BETA4) return PUBLIC_PRESET_ACANTHOSTEGA_BETA4;
  if (preset === UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7) return PUBLIC_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7;
  if (preset === UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION) return PUBLIC_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION;
  if (preset === UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE) return PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE;
  if (preset === UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT) return PUBLIC_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT;
  if (preset === UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION) return PUBLIC_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION;
  if (preset === UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS) return PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS;
  if (preset === UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION) return PUBLIC_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION;
  if (preset === UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION) return PUBLIC_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION;
  if (preset === UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR) return PUBLIC_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR;
  if (preset === UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT) return PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT;
  if (preset === UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION) return PUBLIC_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION;
  if (preset === UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW) return PUBLIC_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW;
  if (preset === UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP) return PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP;
  if (preset === UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER) return PUBLIC_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER;
  if (preset === UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT) return PUBLIC_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT;
  if (preset === UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT) return PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT;
  if (preset === UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_STATIC_TRACTION) return PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_STATIC_TRACTION;
  if (preset === UI_PRESET_ACANTHOSTEGA_STATIC_TRACTION) return PUBLIC_PRESET_ACANTHOSTEGA_STATIC_TRACTION;
  if (preset === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_SURFACE_GEOMETRY) return PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_SURFACE_GEOMETRY;
  if (preset === UI_PRESET_ACANTHOSTEGA_BODY_NORMAL_LOAD_TRACTION) return PUBLIC_PRESET_ACANTHOSTEGA_BODY_NORMAL_LOAD_TRACTION;
  if (preset === UI_PRESET_ACANTHOSTEGA_SURFACE_ELEVATION_SUPPORT) return PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_ELEVATION_SUPPORT;
  if (preset === UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_GROUND_FRICTION) return PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_GROUND_FRICTION;
  if (preset === UI_PRESET_ACANTHOSTEGA_FLAT_GROUND_GRAVITY) return PUBLIC_PRESET_ACANTHOSTEGA_FLAT_GROUND_GRAVITY;
  if (preset === UI_PRESET_ACANTHOSTEGA_EFFECTOR_WORK_ACCOUNTING) return PUBLIC_PRESET_ACANTHOSTEGA_EFFECTOR_WORK_ACCOUNTING;
  if (preset === UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_TRANSLATIONAL_IMPULSE) return PUBLIC_PRESET_ACANTHOSTEGA_HELD_OBJECT_TRANSLATIONAL_IMPULSE;
  if (preset === UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT) return PUBLIC_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT;
  if (preset === UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS) return PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS;
  if (preset === UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE) return PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE;
  if (preset === UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT) return PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT;
  if (preset === UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS) return PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS;
  if (preset === UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE) return PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE;
  if (preset === UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT) return PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT;
  if (preset === UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS) return PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS;
  if (preset === UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS) return PUBLIC_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS;
  if (preset === UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL) return PUBLIC_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL;
  if (preset === UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER) return PUBLIC_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER;
  if (preset === UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS) return PUBLIC_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS;
  if (preset === UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT) return PUBLIC_PRESET_ACANTHOSTEGA_MULTI_CONTENT;
  if (preset === UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL) return PUBLIC_PRESET_ACANTHOSTEGA_WORLD_MATERIAL;
  if (preset === UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL) return PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL;
  if (preset === UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION) return PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION;
  if (preset === UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE) return PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE;
  if (preset === UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION) return PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_TRACTION;
  if (preset === UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION) return PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION;
  if (preset === UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES) return PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES;
  if (preset === UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE) return PUBLIC_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE;
  if (preset === UI_PRESET_ACANTHOSTEGA_MATERIALS) return PUBLIC_PRESET_ACANTHOSTEGA_MATERIALS;
  return undefined;
}

export function uiPresetFromPublic(publicPreset: string | null | undefined): string | null {
  const id = String(publicPreset || '').toUpperCase();
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_BETA4 || id === 'ACANTHOSTEGA_BETA4_0' || id === 'BETA4_0') return UI_PRESET_ACANTHOSTEGA_BETA4;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7 || (id.includes('VOLUMETRIC_WORLD') && id.includes('VW7'))) return UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION || (id.includes('RELEASE') && id.includes('EXCAVATION') && id.includes('SUPPORT_LOSS'))) return UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION || (id.includes('VERTICAL_IMPACT') && id.includes('ACOUSTIC'))) return UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE || (id.includes('VERTICAL_TERRAIN') && id.includes('LANDING'))) return UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT || (id.includes('FREE_SPACE') && id.includes('PE_AUTHORITY'))) return UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION || (id.includes('HELD_DEPOSITION') && id.includes('RADIUS_SHRINK'))) return UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION || (id.includes('HELD_COMBINE') && id.includes('RADIUS_RESIZE'))) return UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS || (id.includes('AMOUNT_SCALED') && id.includes('COLLISION_RADIUS'))) return UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT || (id.includes('CROWDED') && id.includes('PLACEMENT') && id.includes('RETRY'))) return UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION || (id.includes('ACTIVE_LOCOMOTION') && id.includes('TRACTION') && id.includes('SLIDING'))) return UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION || (id.includes('REPEATED') && id.includes('CONSERVATIVE') && id.includes('SURFACE_COLUMN'))) return UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR || (id.includes('BNLT') && id.includes('BREAKAWAY') && id.includes('LOCOMOTION'))) return UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT || (id.includes('DETACHED') && id.includes('TERRAIN') && id.includes('INITIAL_PLACEMENT'))) return UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION || (id.includes('HELD') && id.includes('MEDIATED') && id.includes('SURFACE_EXERTION'))) return UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION || (id.includes('HELD') && id.includes('TERRAIN') && id.includes('MECHANICAL_TRANSMISSION'))) return UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY || (id.includes('HELD') && id.includes('TERRAIN') && id.includes('CONTACT') && !id.includes('MECHANICAL_TRANSMISSION') && !id.includes('FOREIGN'))) return UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE || (id.includes('SURFACE_EXERTION') && id.includes('TERRAIN') && id.includes('RESISTANCE'))) return UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_EFFECTOR_BOUNDED_ACTUATOR_EFFORT || (id.includes('BOUNDED') && id.includes('ACTUATOR') && id.includes('EFFORT'))) return UI_PRESET_ACANTHOSTEGA_EFFECTOR_BOUNDED_ACTUATOR_EFFORT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_MANIPULATOR_RELATIVE_WORLD_ACTUATION || (id.includes('MANIPULATOR') && id.includes('RELATIVE') && id.includes('ACTUATION'))) return UI_PRESET_ACANTHOSTEGA_MANIPULATOR_RELATIVE_WORLD_ACTUATION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_EFFECTOR_TERRAIN_CONTACT_GEOMETRY || (id.includes('EFFECTOR') && id.includes('TERRAIN') && id.includes('CONTACT'))) return UI_PRESET_ACANTHOSTEGA_EFFECTOR_TERRAIN_CONTACT_GEOMETRY;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION || (id.includes('CONSERVATIVE') && id.includes('SURFACE') && id.includes('SEPARATION'))) return UI_PRESET_ACANTHOSTEGA_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_COHERENT_SLOPE_DYNAMICS || (id.includes('COHERENT') && id.includes('SLOPE'))) return UI_PRESET_ACANTHOSTEGA_COHERENT_SLOPE_DYNAMICS;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW || (id.includes('TANGENT') && id.includes('GRAVITY') && id.includes('SHADOW'))) return UI_PRESET_ACANTHOSTEGA_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_PE_POLICY_C || (id.includes('CONTINUOUS_PE_POLICY_C') || (id.includes('CONTINUOUS') && id.includes('PE') && id.includes('POLICY') && !id.includes('SHADOW')))) return UI_PRESET_ACANTHOSTEGA_CONTINUOUS_PE_POLICY_C;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW || (id.includes('ACANTHOSTEGA') && id.includes('CONTINUOUS_GRAVITATIONAL_PE') && id.includes('SHADOW')) || (id.includes('CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW'))) return UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW || (id.includes('ACANTHOSTEGA') && id.includes('DIAGNOSTIC_NORMAL_LOAD_SHADOW')) || (id.includes('CONTINUOUS_NORMAL_LOAD_SHADOW'))) return UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP || (id.includes('ACANTHOSTEGA') && id.includes('RADIUS_AWARE_FACE_SWEEP'))) return UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER || (id.includes('ACANTHOSTEGA') && (id.includes('SES_RUNTIME_CLASSIFIER') || id.includes('SES_RUNTIME_TRANSITION_CLASSIFIER')))) return UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT || (id.includes('ACANTHOSTEGA') && id.includes('SES_DECOMPOSITION_CONTRACT'))) return UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT || (id.includes('ACANTHOSTEGA') && id.includes('RADIUS_AWARE_SUPPORT'))) return UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_STATIC_TRACTION || (id.includes('ACANTHOSTEGA') && id.includes('FREE_OBJECT_STATIC_TRACTION'))) return UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_STATIC_TRACTION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_STATIC_TRACTION || (id.includes('ACANTHOSTEGA') && id.includes('STATIC_TRACTION') && !id.includes('FREE_OBJECT'))) return UI_PRESET_ACANTHOSTEGA_STATIC_TRACTION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_SURFACE_GEOMETRY || (id.includes('ACANTHOSTEGA') && id.includes('CONTINUOUS_SURFACE') && id.includes('GEOMETRY'))) return UI_PRESET_ACANTHOSTEGA_CONTINUOUS_SURFACE_GEOMETRY;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_BODY_NORMAL_LOAD_TRACTION || (id.includes('ACANTHOSTEGA') && id.includes('BODY_NORMAL_LOAD') && id.includes('TRACTION'))) return UI_PRESET_ACANTHOSTEGA_BODY_NORMAL_LOAD_TRACTION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_ELEVATION_SUPPORT || (id.includes('ACANTHOSTEGA') && id.includes('SURFACE_ELEVATION') && id.includes('SUPPORT'))) return UI_PRESET_ACANTHOSTEGA_SURFACE_ELEVATION_SUPPORT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_GROUND_FRICTION || (id.includes('ACANTHOSTEGA') && id.includes('GROUND_FRICTION'))) return UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_GROUND_FRICTION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_FLAT_GROUND_GRAVITY || (id.includes('ACANTHOSTEGA') && id.includes('FLAT_GROUND') && id.includes('GRAVITY') && !id.includes('FRICTION'))) return UI_PRESET_ACANTHOSTEGA_FLAT_GROUND_GRAVITY;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_EFFECTOR_WORK_ACCOUNTING || (id.includes('ACANTHOSTEGA') && id.includes('EFFECTOR') && id.includes('WORK') && id.includes('ACCOUNT'))) return UI_PRESET_ACANTHOSTEGA_EFFECTOR_WORK_ACCOUNTING;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_HELD_OBJECT_TRANSLATIONAL_IMPULSE || (id.includes('ACANTHOSTEGA') && id.includes('HELD') && id.includes('TRANSLATIONAL') && id.includes('IMPULSE'))) return UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_TRANSLATIONAL_IMPULSE;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT || (id.includes('ACANTHOSTEGA') && id.includes('HELD') && id.includes('FOREIGN') && id.includes('CONTACT') && !id.includes('IMPULSE') && !id.includes('ACOUSTIC'))) return UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS || (id.includes('ACANTHOSTEGA') && id.includes('IMPACT') && id.includes('ACOUSTIC') && (id.includes('OBJECT_OBJECT') || (id.match(/OBJECT/g) || []).length >= 2 || id.includes('PAIR')))) return UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE || (id.includes('ACANTHOSTEGA') && id.includes('OBJECT') && id.includes('IMPULSE') && !id.includes('BODY') && !id.includes('IMPACT') && !id.includes('ACOUSTIC') && (id.includes('OBJECT_OBJECT') || (id.match(/OBJECT/g) || []).length >= 2 || id.includes('PAIR')))) return UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT || (id.includes('ACANTHOSTEGA') && id.includes('OBJECT') && id.includes('CONTACT') && !id.includes('BODY') && !id.includes('IMPACT') && !id.includes('ACOUSTIC') && !id.includes('IMPULSE') && (id.includes('OBJECT_OBJECT') || (id.match(/OBJECT/g) || []).length >= 2 || id.includes('PAIR')))) return UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS || (id.includes('ACANTHOSTEGA') && id.includes('OBJECT') && id.includes('IMPACT') && id.includes('ACOUSTIC') && !id.includes('OBJECT_OBJECT') && (id.match(/OBJECT/g) || []).length < 2 && !id.includes('PAIR'))) return UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE || (id.includes('ACANTHOSTEGA') && id.includes('BODY') && id.includes('OBJECT') && id.includes('IMPULSE') && !id.includes('IMPACT') && !id.includes('ACOUSTIC'))) return UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT || (id.includes('ACANTHOSTEGA') && id.includes('BODY') && id.includes('OBJECT') && id.includes('CONTACT') && !id.includes('ACOUSTIC') && !id.includes('IMPULSE'))) return UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS || (id.includes('ACANTHOSTEGA') && id.includes('FREE') && id.includes('OBJECT') && id.includes('KINEMATICS'))) return UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS || (id.includes('ACANTHOSTEGA') && id.includes('CONTACT') && id.includes('ACOUSTIC'))) return UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL || (id.includes('ACANTHOSTEGA') && id.includes('LOCAL') && id.includes('SIGNAL'))) return UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER || (id.includes('COLUMN') && id.includes('TRANSFER'))) return UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS || (id.includes('PROCEDURAL') && id.includes('COLUMN'))) return UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_MULTI_CONTENT || id.includes('MULTI_CONTENT')) return UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_WORLD_MATERIAL || id.includes('WORLD_MATERIAL')) return UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL || id.includes('SURFACE_OPTICAL')) return UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION || id.includes('TRACTION_ADAPTATION')) return UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE || id.includes('TRACTION_EXPERIENCE')) return UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_TRACTION || id.includes('SURFACE_TRACTION')) return UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION || id.includes('SURFACE_DEPOSITION')) return UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES || id.includes('MATERIAL_PROPERTIES')) return UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE || id.includes('COMPOSITION_MERGE')) return UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE;
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_BRING_TOGETHER || id.includes('BRING')) {
    return UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER;
  }
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_BILATERAL_GRASP || id.includes('BILATERAL')) {
    return UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP;
  }
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_SINGLE_GRASP || id.includes('GRASP')) {
    return UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP;
  }
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_VISION || (id.includes('MATERIAL') && id.includes('VISION'))) {
    return UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION;
  }
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_MATERIALS || (id.includes('MATERIALS') && !id.includes('VISION'))) {
    return UI_PRESET_ACANTHOSTEGA_MATERIALS;
  }
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_GENTLE || (id.includes('PHASE_A') && !id.includes('MATERIALS') && !id.includes('MATERIAL_PROPERTIES') && !id.includes('SURFACE_DEPOSITION') && !id.includes('SURFACE_TRACTION') && !id.includes('SURFACE_OPTICAL') && !id.includes('TRACTION_ADAPTATION') && !id.includes('TRACTION_EXPERIENCE') && !id.includes('VISION') && !id.includes('GRASP') && !id.includes('BRING'))) {
    return UI_PRESET_ACANTHOSTEGA_PHASE_A;
  }
  if (id === PUBLIC_PRESET_ACANTHOSTEGA_PHASE0 || id === 'ACANTHOSTEGA') return UI_PRESET_ACANTHOSTEGA_PHASE0;
  if (id === PUBLIC_PRESET_BETA3 || id === 'BETA3') return UI_PRESET_TIKTAALIK_BETA3;
  if (id === PUBLIC_PRESET_TIKTAALIK_BETA31 || id === 'BETA31') return UI_PUBLIC_LABEL_TIKTAALIK_BETA31;
  return null;
}

export function modelLineFromPublicPreset(publicPreset: string | null | undefined): 'TIKTAALIK' | 'ACANTHOSTEGA' {
  const id = String(publicPreset || '').toUpperCase();
  if (id.includes('ACANTHOSTEGA')) return 'ACANTHOSTEGA';
  return 'TIKTAALIK';
}

export function modelLineFromUiPreset(preset: string): 'TIKTAALIK' | 'ACANTHOSTEGA' {
  return preset === UI_PRESET_ACANTHOSTEGA_PHASE0
    || preset === UI_PRESET_ACANTHOSTEGA_PHASE_A
    || preset === UI_PRESET_ACANTHOSTEGA_MATERIALS
    || preset === UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION
    || preset === UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP
    || preset === UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP
    || preset === UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER
    || preset === UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE
    || preset === UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES
    || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION
    || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION
    || preset === UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE
    || preset === UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION
    || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL
    || preset === UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL
    || preset === UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT
    || preset === UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS
    || preset === UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER
    || preset === UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL
    || preset === UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS
    || preset === UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS
    || preset === UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT
    || preset === UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE
    || preset === UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS
    || preset === UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT
    || preset === UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE
    || preset === UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS || preset === UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT || preset === UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_TRANSLATIONAL_IMPULSE || preset === UI_PRESET_ACANTHOSTEGA_EFFECTOR_WORK_ACCOUNTING || preset === UI_PRESET_ACANTHOSTEGA_FLAT_GROUND_GRAVITY || preset === UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_GROUND_FRICTION || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_ELEVATION_SUPPORT || preset === UI_PRESET_ACANTHOSTEGA_BODY_NORMAL_LOAD_TRACTION || preset === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_SURFACE_GEOMETRY || preset === UI_PRESET_ACANTHOSTEGA_STATIC_TRACTION || preset === UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_STATIC_TRACTION || preset === UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT || preset === UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT || preset === UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER || preset === UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP || preset === UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW || preset === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW || preset === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_PE_POLICY_C || preset === UI_PRESET_ACANTHOSTEGA_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW || preset === UI_PRESET_ACANTHOSTEGA_COHERENT_SLOPE_DYNAMICS || preset === UI_PRESET_ACANTHOSTEGA_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION || preset === UI_PRESET_ACANTHOSTEGA_EFFECTOR_TERRAIN_CONTACT_GEOMETRY || preset === UI_PRESET_ACANTHOSTEGA_MANIPULATOR_RELATIVE_WORLD_ACTUATION     || preset === UI_PRESET_ACANTHOSTEGA_EFFECTOR_BOUNDED_ACTUATOR_EFFORT || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE || preset === UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY || preset === UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION || preset === UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION || preset === UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT || preset === UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR || preset === UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION || preset === UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION || preset === UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT     || preset === UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS || preset === UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION     || preset === UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION || preset === UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT || preset === UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE || preset === UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION || preset === UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION || preset === UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7 || preset === UI_PRESET_ACANTHOSTEGA_BETA4
    ? 'ACANTHOSTEGA'
    : 'TIKTAALIK';
}

export function isNamedCanonicalUiPreset(preset: string): boolean {
  return preset === UI_PRESET_TIKTAALIK_BETA31
    || preset === UI_PRESET_TIKTAALIK_BETA3
    || preset === UI_PRESET_ACANTHOSTEGA_PHASE0
    || preset === UI_PRESET_ACANTHOSTEGA_PHASE_A
    || preset === UI_PRESET_ACANTHOSTEGA_MATERIALS
    || preset === UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION
    || preset === UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP
    || preset === UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP
    || preset === UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER
    || preset === UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE
    || preset === UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES
    || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION
    || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION
    || preset === UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE
    || preset === UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION
    || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL
    || preset === UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL
    || preset === UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT
    || preset === UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS
    || preset === UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER
    || preset === UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL
    || preset === UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS
    || preset === UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS
    || preset === UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT
    || preset === UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE
    || preset === UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS
    || preset === UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT
    || preset === UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE
    || preset === UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS || preset === UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT || preset === UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_TRANSLATIONAL_IMPULSE || preset === UI_PRESET_ACANTHOSTEGA_EFFECTOR_WORK_ACCOUNTING || preset === UI_PRESET_ACANTHOSTEGA_FLAT_GROUND_GRAVITY || preset === UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_GROUND_FRICTION || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_ELEVATION_SUPPORT || preset === UI_PRESET_ACANTHOSTEGA_BODY_NORMAL_LOAD_TRACTION || preset === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_SURFACE_GEOMETRY || preset === UI_PRESET_ACANTHOSTEGA_STATIC_TRACTION || preset === UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_STATIC_TRACTION || preset === UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT || preset === UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT || preset === UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER || preset === UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP || preset === UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW || preset === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW || preset === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_PE_POLICY_C || preset === UI_PRESET_ACANTHOSTEGA_TANGENT_GRAVITY_DIAGNOSTIC_SHADOW || preset === UI_PRESET_ACANTHOSTEGA_COHERENT_SLOPE_DYNAMICS || preset === UI_PRESET_ACANTHOSTEGA_CONSERVATIVE_SURFACE_MATERIAL_SEPARATION || preset === UI_PRESET_ACANTHOSTEGA_EFFECTOR_TERRAIN_CONTACT_GEOMETRY || preset === UI_PRESET_ACANTHOSTEGA_MANIPULATOR_RELATIVE_WORLD_ACTUATION     || preset === UI_PRESET_ACANTHOSTEGA_EFFECTOR_BOUNDED_ACTUATOR_EFFORT || preset === UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE || preset === UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY || preset === UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION || preset === UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION || preset === UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT
    || preset === UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR
    || preset === UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION
    || preset === UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION
    || preset === UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT
    || preset === UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS
    || preset === UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION
    || preset === UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION
    || preset === UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT
    || preset === UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE
    || preset === UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION
    || preset === UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION || preset === UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7 || preset === UI_PRESET_ACANTHOSTEGA_BETA4;
}

export function presetModifiedStatusLabel(preset: string, modified: boolean): string {
  if (preset === UI_PRESET_CUSTOM) return 'CUSTOM';
  return modified ? `${preset} — Modified` : preset;
}

export function compatPublicPreset(raw: string | null | undefined): 'TIKTAALIK' | 'ACANTHOSTEGA' {
  if (raw == null || String(raw).trim() === '') return 'TIKTAALIK';
  return modelLineFromPublicPreset(raw);
}
