import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import {
  CANONICAL_MODEL_PRESETS as G2C1_CANONICAL_MODEL_PRESETS,
  UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT,
  PUBLIC_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT,
  UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER,
  PUBLIC_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER,
  UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP,
  UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW,
  UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW,
  PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP,
  PUBLIC_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW,
  PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW,
  UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE,
  PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE,
  UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY,
  PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY,
  UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION,
  PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION,
  UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION,
  PUBLIC_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION,
  UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT,
  PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT,
  UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR,
  PUBLIC_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR,
  UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION,
  PUBLIC_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION,
  UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION,
  PUBLIC_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION,
  UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT,
  PUBLIC_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT,
  UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS,
  PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS,
  UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION,
  PUBLIC_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION,
  UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION,
  PUBLIC_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION,
  UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT,
  PUBLIC_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT,
  UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE,
  PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE,
  UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION,
  PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION,
  UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION,
  UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7,
  UI_PRESET_ACANTHOSTEGA_BETA4,
  UI_PUBLIC_LABEL_TIKTAALIK_BETA31,
  PUBLIC_MODEL_PRESETS,
  isPublicModelSelectorEntry,
  PUBLIC_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION,
  PUBLIC_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7,
  PUBLIC_PRESET_ACANTHOSTEGA_BETA4,
  UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT as G2C1_PARENT_UI,
  PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_SUPPORT as G2C1_PARENT_PUBLIC,
  publicPresetFromUi as g2c1PublicPresetFromUi,
  uiPresetFromPublic as g2c1UiPresetFromPublic,
  modelLineFromUiPreset as g2c1ModelLineFromUiPreset,
  modelLineFromPublicPreset as g2c1ModelLineFromPublicPreset,
  isNamedCanonicalUiPreset as g2c1IsNamedCanonicalUiPreset,
} from './modelPreset.ts';
import {
  CANONICAL_MODEL_PRESETS,
  UI_PRESET_ACANTHOSTEGA_PHASE0,
  UI_PRESET_ACANTHOSTEGA_PHASE_A,
  UI_PRESET_ACANTHOSTEGA_MATERIALS,
  UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION,
  UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP,
  UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP,
  UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER,
  UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE,
  UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES,
  UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION,
  UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION,
  UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE,
  UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION,
  UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL,
  UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL,
  UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT,
  UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS,
  UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER,
  UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL,
  UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS,
  UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS,
  UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT,
  UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE,
  UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS,
  UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT,
  UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE,
  UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS,
  UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT,
  UI_PRESET_TIKTAALIK_BETA31,
  UI_PRESET_CUSTOM,
  PUBLIC_PRESET_ACANTHOSTEGA_PHASE0,
  PUBLIC_PRESET_ACANTHOSTEGA_GENTLE,
  PUBLIC_PRESET_ACANTHOSTEGA_MATERIALS,
  PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_VISION,
  PUBLIC_PRESET_ACANTHOSTEGA_SINGLE_GRASP,
  PUBLIC_PRESET_ACANTHOSTEGA_BILATERAL_GRASP,
  PUBLIC_PRESET_ACANTHOSTEGA_BRING_TOGETHER,
  PUBLIC_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE,
  PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES,
  PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION,
  PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_TRACTION,
  PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE,
  PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION,
  PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL,
  PUBLIC_PRESET_ACANTHOSTEGA_WORLD_MATERIAL,
  PUBLIC_PRESET_ACANTHOSTEGA_MULTI_CONTENT,
  PUBLIC_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS,
  PUBLIC_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER,
  PUBLIC_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL,
  PUBLIC_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS,
  PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS,
  PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT,
  PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE,
  PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS,
  PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT,
  PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE,
  PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS,
  PUBLIC_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT,
  PUBLIC_PRESET_TIKTAALIK_BETA31,
  compatPublicPreset,
  modelLineFromUiPreset,
  modelLineFromPublicPreset,
  isNamedCanonicalUiPreset,
  presetModifiedStatusLabel,
  publicPresetFromUi,
  uiPresetFromPublic,
} from './modelPreset.ts';

describe('canonical model preset selector', () => {
  it('lists Tiktaalik Beta 3.1 and Acanthostega stages including Material Vision', () => {
    assert.deepEqual([...CANONICAL_MODEL_PRESETS], [
      UI_PRESET_TIKTAALIK_BETA31,
      UI_PRESET_ACANTHOSTEGA_PHASE0,
      UI_PRESET_ACANTHOSTEGA_PHASE_A,
      UI_PRESET_ACANTHOSTEGA_MATERIALS,
      UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION,
      UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP,
      UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP,
      UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER,
      UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE,
      UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES,
      UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION,
      UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION,
      UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE,
      UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION,
      UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL,
      UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL,
      UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT,
      UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS,
      UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER,
      UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL,
      UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS,
      UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS,
      UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT,
      UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE,
      UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS,
      UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT,
      UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE,
      UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS,
      UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT,
      'Acanthostega Phase B Held Object Translational Impulse',
      'Acanthostega Phase B Effector Work Accounting',
      'Acanthostega Phase C Flat Ground Gravity',
      'Acanthostega Phase C Free Object Ground Friction',
      'Acanthostega Phase C Surface Elevation Support',
      'Acanthostega Phase C Body Normal-Load Traction',
      'Acanthostega Phase C Continuous Surface Geometry',
      'Acanthostega Phase C Static Traction',
      'Acanthostega Phase C Free Object Static Traction',
      G2C1_PARENT_UI,
      UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT,
      UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER,
      UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP,
      UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW,
      UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW,
      'Acanthostega Phase C Continuous PE Policy C',
      'Acanthostega Phase C Tangent Gravity Diagnostic Shadow',
      'Acanthostega Phase C Coherent Slope Dynamics',
      'Acanthostega Beta 4 Conservative Surface Material Separation',
      'Acanthostega Beta 4 Effector Terrain Contact Geometry',
      'Acanthostega Beta 4 Manipulator Relative World Actuation',
      'Acanthostega Beta 4 Effector Bounded Actuator Effort',
      UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE,
      UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY,
      UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION,
      UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION,
      UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT,
      UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR,
      UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION,
      UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION,
      UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT,
      UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS,
      UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION,
      UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION,
      UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT,
      UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE,
      UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION,
      UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION,
      UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7,
      UI_PRESET_ACANTHOSTEGA_BETA4,
    ]);
    assert.equal(new Set(CANONICAL_MODEL_PRESETS).size, CANONICAL_MODEL_PRESETS.length);
  });

  it('defaults mapping for Tiktaalik Beta 3.1', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_TIKTAALIK_BETA31), PUBLIC_PRESET_TIKTAALIK_BETA31);
    assert.equal(modelLineFromUiPreset(UI_PRESET_TIKTAALIK_BETA31), 'TIKTAALIK');
  });

  it('maps Acanthostega Phase 0 to its own public_preset and model_line', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_PHASE0), PUBLIC_PRESET_ACANTHOSTEGA_PHASE0);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_PHASE0), 'ACANTHOSTEGA');
  });

  it('maps Acanthostega Phase A Materials to its public_preset', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_MATERIALS), PUBLIC_PRESET_ACANTHOSTEGA_MATERIALS);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_MATERIALS), 'ACANTHOSTEGA');
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_MATERIALS), UI_PRESET_ACANTHOSTEGA_MATERIALS);
  });

  it('maps Acanthostega Phase A Material Vision separately from Materials', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION), PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_VISION);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_VISION), UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_VISION), UI_PRESET_ACANTHOSTEGA_MATERIALS);
  });

  it('maps Acanthostega Phase A Bilateral Grasp separately from Single Grasp', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP), PUBLIC_PRESET_ACANTHOSTEGA_BILATERAL_GRASP);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BILATERAL_GRASP), UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BILATERAL_GRASP), UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP);
  });

  it('maps Acanthostega Phase A Bring Together separately from Bilateral Grasp', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER), PUBLIC_PRESET_ACANTHOSTEGA_BRING_TOGETHER);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BRING_TOGETHER), UI_PRESET_ACANTHOSTEGA_BRING_TOGETHER);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BRING_TOGETHER), UI_PRESET_ACANTHOSTEGA_BILATERAL_GRASP);
  });

  it('maps Traction Adaptation separately from Traction Experience', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION), PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION), UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL), UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_WORLD_MATERIAL), UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_MULTI_CONTENT), UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_MULTI_CONTENT), UI_PRESET_ACANTHOSTEGA_WORLD_MATERIAL);
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS), PUBLIC_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS), UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS), UI_PRESET_ACANTHOSTEGA_MULTI_CONTENT);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS), 'ACANTHOSTEGA');
    assert.equal(UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER, 'Acanthostega Phase B Column Transfer');
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER), PUBLIC_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER), UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER), UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS), UI_PRESET_ACANTHOSTEGA_PROCEDURAL_COLUMNS);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER), 'ACANTHOSTEGA');
    assert.equal(UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL, 'Acanthostega Phase B Local Physical Signal');
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL), PUBLIC_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL), UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL), UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER), UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL), 'ACANTHOSTEGA');
    assert.equal(UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS, 'Acanthostega Phase B Contact Acoustics');
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS), PUBLIC_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS), UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS), UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL), UI_PRESET_ACANTHOSTEGA_LOCAL_SIGNAL);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS), 'ACANTHOSTEGA');
    assert.equal(UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS, 'Acanthostega Phase B Free Object Kinematics');
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS), PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS), UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS), UI_PRESET_ACANTHOSTEGA_COLUMN_TRANSFER);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS), UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS), 'ACANTHOSTEGA');
    assert.equal(UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT, 'Acanthostega Phase B Body Object Contact');
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT), PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT), UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT), UI_PRESET_ACANTHOSTEGA_FREE_OBJECT_KINEMATICS);
    assert.equal(UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE, 'Acanthostega Phase B Body Object Impulse');
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE), PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE), UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE), UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_CONTACT);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE), 'ACANTHOSTEGA');
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_WORLD_MATERIAL), UI_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_WORLD_MATERIAL), UI_PRESET_ACANTHOSTEGA_PHASE_A);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL), UI_PRESET_ACANTHOSTEGA_PHASE_A);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_OPTICAL), UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION), 'ACANTHOSTEGA');
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION), UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_ADAPTATION), UI_PRESET_ACANTHOSTEGA_PHASE_A);
  });

  it('maps Traction Experience separately from Surface Traction', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE), PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE), UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE), 'ACANTHOSTEGA');
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE), UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_TRACTION_EXPERIENCE), UI_PRESET_ACANTHOSTEGA_PHASE_A);
  });

  it('maps Surface Traction separately from Surface Deposition', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION), PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_TRACTION);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_TRACTION), UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_SURFACE_TRACTION), 'ACANTHOSTEGA');
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_TRACTION), UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_TRACTION), UI_PRESET_ACANTHOSTEGA_PHASE_A);
  });

  it('maps Surface Deposition separately from Material Properties', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION), PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION), UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION), 'ACANTHOSTEGA');
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION), UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SURFACE_DEPOSITION), UI_PRESET_ACANTHOSTEGA_PHASE_A);
  });

  it('maps Material Properties separately from Composition Merge', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES), PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES), UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES), 'ACANTHOSTEGA');
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_MATERIAL_PROPERTIES), UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE);
  });

  it('maps Composition Merge separately and round-trips', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE), PUBLIC_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE), UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_COMPOSITION_MERGE), 'ACANTHOSTEGA');
  });

  it('maps Acanthostega Phase A Single Grasp', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP), PUBLIC_PRESET_ACANTHOSTEGA_SINGLE_GRASP);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SINGLE_GRASP), UI_PRESET_ACANTHOSTEGA_SINGLE_GRASP);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SINGLE_GRASP), UI_PRESET_ACANTHOSTEGA_MATERIAL_VISION);
  });

  it('does not map Tiktaalik Beta 3.1 to Acanthostega', () => {
    assert.notEqual(publicPresetFromUi(UI_PRESET_TIKTAALIK_BETA31), PUBLIC_PRESET_ACANTHOSTEGA_PHASE0);
    assert.equal(modelLineFromUiPreset(UI_PRESET_TIKTAALIK_BETA31), 'TIKTAALIK');
  });

  it('treats missing public_preset as Tiktaalik', () => {
    assert.equal(compatPublicPreset(null), 'TIKTAALIK');
    assert.equal(compatPublicPreset(undefined), 'TIKTAALIK');
    assert.equal(compatPublicPreset(''), 'TIKTAALIK');
    assert.equal(uiPresetFromPublic(null), null);
  });

  it('round-trips public_preset to UI label', () => {
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_PHASE0), UI_PRESET_ACANTHOSTEGA_PHASE0);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_TIKTAALIK_BETA31), UI_PUBLIC_LABEL_TIKTAALIK_BETA31);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_GENTLE), UI_PRESET_ACANTHOSTEGA_PHASE_A);
  });

  it('shows Modified without renaming the base preset', () => {
    assert.equal(
      presetModifiedStatusLabel(UI_PRESET_ACANTHOSTEGA_PHASE0, true),
      'Acanthostega Phase 0 — Modified',
    );
    assert.equal(presetModifiedStatusLabel(UI_PRESET_ACANTHOSTEGA_PHASE0, false), UI_PRESET_ACANTHOSTEGA_PHASE0);
    assert.equal(
      presetModifiedStatusLabel(UI_PRESET_TIKTAALIK_BETA31, true),
      'MM 1.0 — Tiktaalik Beta 3.1 — Modified',
    );
  });
});

  it('maps Acanthostega Phase B Object Impact Acoustics separately from Body Object Impulse and Contact Acoustics', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS), PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS), UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS);
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT), PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT);
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT), PUBLIC_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT), UI_PRESET_ACANTHOSTEGA_HELD_OBJECT_FOREIGN_BODY_CONTACT);
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS), PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS), UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPACT_ACOUSTICS), UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE);
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE), PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE), UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_IMPULSE), UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT), UI_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_OBJECT_CONTACT), UI_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS), UI_PRESET_ACANTHOSTEGA_BODY_OBJECT_IMPULSE);
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_OBJECT_IMPACT_ACOUSTICS), UI_PRESET_ACANTHOSTEGA_CONTACT_ACOUSTICS);
  });


describe('G2C1 SES Decomposition Contract preset (single canonical selector)', () => {
  it('is present exactly once in the canonical selector list, after its G2B parent', () => {
    const list = [...G2C1_CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT).length, 1);
    assert.ok(list.indexOf(UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT) > list.indexOf(G2C1_PARENT_UI));
  });
  it('round-trips UI <-> public id and keeps Acanthostega identity', () => {
    assert.equal(g2c1PublicPresetFromUi(UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT), PUBLIC_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT);
    assert.equal(g2c1UiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT), UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT);
    assert.equal(g2c1ModelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT), 'ACANTHOSTEGA');
    assert.equal(g2c1ModelLineFromPublicPreset(PUBLIC_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT), 'ACANTHOSTEGA');
    assert.equal(g2c1IsNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT), true);
  });
  it('does not collapse into or steal the G2B parent mapping', () => {
    assert.equal(g2c1UiPresetFromPublic(G2C1_PARENT_PUBLIC), G2C1_PARENT_UI);
    assert.equal(g2c1PublicPresetFromUi(G2C1_PARENT_UI), G2C1_PARENT_PUBLIC);
    assert.notEqual(g2c1UiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT), G2C1_PARENT_UI);
  });
});

describe('G2C2 SES Runtime Classifier preset (single canonical selector)', () => {
  it('is present exactly once, directly after its G2C1 parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER).length, 1);
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT) + 1,
    );
  });
  it('round-trips UI <-> public id and keeps Acanthostega identity', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER), PUBLIC_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER), UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER), 'ACANTHOSTEGA');
    assert.equal(modelLineFromPublicPreset(PUBLIC_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER), 'ACANTHOSTEGA');
    assert.equal(isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER), true);
  });
  it('does not collapse into G2C1 parent mapping', () => {
    assert.notEqual(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER), UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT), UI_PRESET_ACANTHOSTEGA_SES_DECOMPOSITION_CONTRACT);
  });
});

describe('Radius-Aware Face Sweep preset (single canonical selector)', () => {
  it('is present exactly once, directly after its G2C2 parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP).length, 1);
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_SES_RUNTIME_CLASSIFIER) + 1,
    );
  });
  it('round-trips UI <-> public id and keeps Acanthostega identity', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP), PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP), UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP), 'ACANTHOSTEGA');
    assert.equal(modelLineFromPublicPreset(PUBLIC_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP), 'ACANTHOSTEGA');
    assert.equal(isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP), true);
  });
});


describe('Diagnostic Normal-Load Shadow preset (single canonical selector)', () => {
  it('appears exactly once after face sweep', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW).length, 1);
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_RADIUS_AWARE_FACE_SWEEP) + 1,
    );
  });
  it('maps public <-> UI', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW), PUBLIC_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW), UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW), 'ACANTHOSTEGA');
    assert.equal(modelLineFromPublicPreset(PUBLIC_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW), 'ACANTHOSTEGA');
    assert.equal(isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW), true);
  });
});


describe('Continuous Gravitational PE Diagnostic Shadow preset (single canonical selector)', () => {
  it('appears exactly once after diagnostic normal-load shadow', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW).length, 1);
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_DIAGNOSTIC_NORMAL_LOAD_SHADOW) + 1,
    );
  });
  it('maps public <-> UI', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW),
      PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW),
      UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW,
    );
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW), 'ACANTHOSTEGA');
    assert.equal(modelLineFromPublicPreset(PUBLIC_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW), 'ACANTHOSTEGA');
    assert.equal(isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_CONTINUOUS_GRAVITATIONAL_PE_DIAGNOSTIC_SHADOW), true);
  });
});

describe('Held ResourceObject Terrain Contact Geometry preset (Beta 4)', () => {
  it('appears exactly once immediately after Surface Exertion parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY),
      PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY),
      UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY),
      'ACANTHOSTEGA',
    );
    assert.equal(
      modelLineFromPublicPreset(PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY),
      true,
    );
  });
  it('does not collapse into parent Surface Exertion mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY),
      UI_PRESET_ACANTHOSTEGA_SURFACE_EXERTION_TERRAIN_MATERIAL_RESISTANCE,
    );
  });
});

describe('Held ResourceObject Terrain Mechanical Transmission preset (Beta 4)', () => {
  it('appears exactly once immediately after Held Terrain Contact parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION),
      PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION),
      UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION),
      'ACANTHOSTEGA',
    );
    assert.equal(
      modelLineFromPublicPreset(PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION),
      true,
    );
  });
  it('does not collapse into parent Held Terrain Contact mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION),
      UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_CONTACT_GEOMETRY,
    );
  });
});

describe('Held-Mediated Surface Exertion Integration preset (Beta 4)', () => {
  it('appears exactly once immediately after Held Terrain Transmission parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION),
      PUBLIC_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION),
      UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION),
      'ACANTHOSTEGA',
    );
    assert.equal(isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION), true);
  });
  it('does not collapse into parent transmission mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION),
      UI_PRESET_ACANTHOSTEGA_HELD_RESOURCE_OBJECT_TERRAIN_MECHANICAL_TRANSMISSION,
    );
  });
});

describe('Detached Terrain Material Initial Placement preset (Beta 4)', () => {
  it('appears exactly once immediately after Held-Mediated parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT),
      PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT),
      UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT),
      'ACANTHOSTEGA',
    );
    assert.equal(isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT), true);
  });
  it('does not collapse into parent HMSI mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT),
      UI_PRESET_ACANTHOSTEGA_HELD_MEDIATED_SURFACE_EXERTION_INTEGRATION,
    );
  });
});

describe('BNLT MOVE Breakaway Locomotion Repair preset (Beta 4)', () => {
  it('appears exactly once immediately after DTIP parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR),
      PUBLIC_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR),
      UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR),
      'ACANTHOSTEGA',
    );
    assert.equal(isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR), true);
  });
  it('does not collapse into parent DTIP mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR),
      UI_PRESET_ACANTHOSTEGA_DETACHED_TERRAIN_MATERIAL_INITIAL_PLACEMENT,
    );
  });
});

describe('Repeated Conservative Surface-Column Separation preset (Beta 4)', () => {
  it('appears exactly once immediately after BNLT repair parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION),
      PUBLIC_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION),
      UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION),
      true,
    );
  });
  it('does not collapse into parent BNLT mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION),
      UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR,
    );
  });
});

describe('Active Locomotion Traction vs Sliding Friction preset (Beta 4)', () => {
  it('appears exactly once immediately after RCSS parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION),
      PUBLIC_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION),
      UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION),
      true,
    );
  });
  it('does not collapse into parent RCSS or BNLT mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION),
      UI_PRESET_ACANTHOSTEGA_REPEATED_CONSERVATIVE_SURFACE_COLUMN_SEPARATION,
    );
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION),
      UI_PRESET_ACANTHOSTEGA_BNLT_MOVE_BREAKAWAY_LOCOMOTION_REPAIR,
    );
  });
});

describe('Event-Driven Crowded Placement Retry Contract preset (Beta 4)', () => {
  it('appears exactly once immediately after ALTVSF parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT),
      PUBLIC_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT),
      UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT),
      true,
    );
  });
  it('does not collapse into parent ALTVSF mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT),
      UI_PRESET_ACANTHOSTEGA_ACTIVE_LOCOMOTION_TRACTION_VS_SLIDING_FRICTION,
    );
  });
});

describe('Detached Material Amount-Scaled Collision Radius preset (Beta 4)', () => {
  it('appears exactly once immediately after crowded-retry parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS),
      PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS),
      UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS),
      true,
    );
  });
  it('does not collapse into crowded-retry parent mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS),
      UI_PRESET_ACANTHOSTEGA_EVENT_DRIVEN_CROWDED_PLACEMENT_RETRY_CONTRACT,
    );
  });
});

describe('Held COMBINE Radius Resize Transaction preset (Beta 4)', () => {
  it('appears exactly once immediately after creation-size parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION),
      PUBLIC_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION),
      UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION),
      true,
    );
  });
  it('does not collapse into creation-size parent mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION),
      UI_PRESET_ACANTHOSTEGA_DETACHED_MATERIAL_AMOUNT_SCALED_COLLISION_RADIUS,
    );
  });
});

describe('Held Deposition Radius Shrink Transaction preset (Beta 4)', () => {
  it('appears exactly once immediately after COMBINE-resize parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION),
      PUBLIC_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION),
      UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION),
      true,
    );
  });
  it('does not collapse into COMBINE-resize parent mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION),
      UI_PRESET_ACANTHOSTEGA_HELD_COMBINE_RADIUS_RESIZE_TRANSACTION,
    );
  });
});

describe('Vertical Terrain Landing Contact Response preset (Beta 4 / V1B)', () => {
  it('appears exactly once immediately after free-space parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE),
      PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE),
      UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE),
      true,
    );
  });
  it('does not collapse into free-space parent mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE),
      UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT,
    );
  });
});

describe('Vertical Impact Acoustic Emission preset (Beta 4 / V1C)', () => {
  it('appears exactly once immediately after landing parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION),
      PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION),
      UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION),
      true,
    );
  });
  it('does not collapse into landing parent mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION),
      UI_PRESET_ACANTHOSTEGA_VERTICAL_TERRAIN_LANDING_CONTACT_RESPONSE,
    );
  });
});

describe('Release And Excavation Support Loss Integration preset (Beta 4 / V1D)', () => {
  it('appears exactly once immediately after V1C parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION),
      PUBLIC_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION),
      UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION),
      true,
    );
  });
  it('does not collapse into V1C parent mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION),
      UI_PRESET_ACANTHOSTEGA_VERTICAL_IMPACT_ACOUSTIC_EMISSION,
    );
  });
});

describe('Free-Space State And PE Authority Contract preset (Beta 4 / V1A)', () => {
  it('appears exactly once immediately after held-deposition parent', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(
      list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT).length,
      1,
    );
    assert.equal(
      list.indexOf(UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT),
      list.indexOf(UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION) + 1,
    );
  });
  it('round-trips UI <-> public and stays Acanthostega', () => {
    assert.equal(
      publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT),
      PUBLIC_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT,
    );
    assert.equal(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT),
      UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT,
    );
    assert.equal(
      modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT),
      'ACANTHOSTEGA',
    );
    assert.equal(
      isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT),
      true,
    );
  });
  it('does not collapse into held-deposition parent mapping', () => {
    assert.notEqual(
      uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_FREE_SPACE_STATE_AND_PE_AUTHORITY_CONTRACT),
      UI_PRESET_ACANTHOSTEGA_HELD_DEPOSITION_RADIUS_SHRINK_TRANSACTION,
    );
  });
});


describe('Volumetric World VW7 cumulative public preset', () => {
  it('appears exactly once after Release/Excavation tip as Acanthostega tip', () => {
    const list = [...CANONICAL_MODEL_PRESETS] as string[];
    assert.equal(list.filter((p) => p === UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7).length, 1);
    const iRel = list.indexOf(UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION);
    const iVw7 = list.indexOf(UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7);
    assert.ok(iRel >= 0 && iVw7 === iRel + 1);
    // Tiktaalik is listed first historically; public Beta 4 tip is last Acanthostega entry
    const iBeta4 = list.indexOf(UI_PRESET_ACANTHOSTEGA_BETA4);
    assert.ok(iBeta4 === iVw7 + 1 || iVw7 >= 0);
    const after = list.slice(Math.max(iVw7, iBeta4) + 1);
    assert.equal(after.filter((p) => String(p).startsWith('Acanthostega')).length, 0);
  });
  it('maps public <-> UI and stays Acanthostega', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7), PUBLIC_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7), UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7), 'ACANTHOSTEGA');
    assert.equal(isNamedCanonicalUiPreset(UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7), true);
  });
});


describe('public model selector boundary', () => {
  it('normal public model selector is exactly two entries', () => {
    assert.deepEqual([...PUBLIC_MODEL_PRESETS], [
      UI_PUBLIC_LABEL_TIKTAALIK_BETA31,
      UI_PRESET_ACANTHOSTEGA_BETA4,
    ]);
    assert.equal(PUBLIC_MODEL_PRESETS.length, 2);
    assert.equal(new Set(PUBLIC_MODEL_PRESETS).size, 2);
  });

  it('classifies only Tiktaalik Beta 3.1 and Acanthostega Beta 4.0 as public', () => {
    assert.equal(isPublicModelSelectorEntry(UI_PUBLIC_LABEL_TIKTAALIK_BETA31), true);
    assert.equal(isPublicModelSelectorEntry(UI_PRESET_ACANTHOSTEGA_BETA4), true);
    assert.equal(isPublicModelSelectorEntry(UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7), false);
    assert.equal(isPublicModelSelectorEntry(UI_PRESET_ACANTHOSTEGA_RELEASE_AND_EXCAVATION_SUPPORT_LOSS_INTEGRATION), false);
    assert.equal(isPublicModelSelectorEntry(UI_PRESET_CUSTOM), false);
    assert.equal(isPublicModelSelectorEntry(UI_PRESET_ACANTHOSTEGA_PHASE0), false);
  });

  it('maps public Beta 4.0 label to ACANTHOSTEGA_BETA4', () => {
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_BETA4), PUBLIC_PRESET_ACANTHOSTEGA_BETA4);
    assert.equal(uiPresetFromPublic(PUBLIC_PRESET_ACANTHOSTEGA_BETA4), UI_PRESET_ACANTHOSTEGA_BETA4);
    assert.equal(modelLineFromUiPreset(UI_PRESET_ACANTHOSTEGA_BETA4), 'ACANTHOSTEGA');
    assert.equal(publicPresetFromUi(UI_PUBLIC_LABEL_TIKTAALIK_BETA31), PUBLIC_PRESET_TIKTAALIK_BETA31);
  });

  it('keeps VW7 fixture resolvable outside the normal selector', () => {
    assert.ok(CANONICAL_MODEL_PRESETS.includes(UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7));
    assert.equal(publicPresetFromUi(UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7), PUBLIC_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7);
    assert.ok(!PUBLIC_MODEL_PRESETS.includes(UI_PRESET_ACANTHOSTEGA_VOLUMETRIC_WORLD_VW7));
  });
});
