"""V3 provenance enums (schema-level; not stamped on every scalar)."""
from __future__ import annotations

PHYSICAL_GROUND_TRUTH = "PHYSICAL_GROUND_TRUTH"
AGENT_ACCESSIBLE = "AGENT_ACCESSIBLE"
COGNITIVE_INTERNAL = "COGNITIVE_INTERNAL"
DECISION_INTERNAL = "DECISION_INTERNAL"
MOTOR_OUTPUT = "MOTOR_OUTPUT"
EXPERIMENTER_CONTROL = "EXPERIMENTER_CONTROL"
CONFIGURATION = "CONFIGURATION"
DERIVED_POSTHOC = "DERIVED_POSTHOC"
LEGACY_COMPATIBILITY = "LEGACY_COMPATIBILITY"
DEBUG_DIAGNOSTIC = "DEBUG_DIAGNOSTIC"

ALL = (
    PHYSICAL_GROUND_TRUTH,
    AGENT_ACCESSIBLE,
    COGNITIVE_INTERNAL,
    DECISION_INTERNAL,
    MOTOR_OUTPUT,
    EXPERIMENTER_CONTROL,
    CONFIGURATION,
    DERIVED_POSTHOC,
    LEGACY_COMPATIBILITY,
    DEBUG_DIAGNOSTIC,
)
